name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'whitesource-remediate/**'
      - 'backport/**'
      - 'create-pull-request/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spotless:
    if: github.repository == 'opensearch-project/flow-framework'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Spotless Check
        run: ./gradlew spotlessCheck
  javadoc:
    if: github.repository == 'opensearch-project/flow-framework'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Javadoc CheckStyle
        run: ./gradlew checkstyleMain
      - name: Javadoc Check
        run: ./gradlew javadoc
  build:
    needs: [spotless, javadoc]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [21]
    name: Test JDK${{ matrix.java }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build and Run Tests
        run: |
          ./gradlew check -x integTest -x yamlRestTest -x spotlessJava
      - name: Upload Coverage Report
        if: contains(matrix.os, 'ubuntu') && contains(matrix.java, '21')
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
  integTest:
    needs: [spotless, javadoc]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [21]
    name: Integ Test JDK${{ matrix.java }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build and Run Tests
        run: |
          ./gradlew integTest yamlRestTest
  integMultiNodeTest:
    needs: [spotless, javadoc]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [21]
    name: Multi-Node Integ Test JDK${{ matrix.java }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build and Run Tests
        run: |
          ./gradlew integTest -PnumNodes=3
  integTenantAwareTest:
    needs: [spotless, javadoc]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [21]
    name: Tenant Aware Integ Test JDK${{ matrix.java }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      # doesn't actually use this client but validates the build
      REMOTE_METADATA_SDK_IMPL: ddb-client
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build and Run Tests
        run: |
          ./gradlew integTest "-Dtests.rest.tenantaware=true"
