name: CI

on:
  push:
    branches-ignore:
      - 'whitesource-remediate/**'
      - 'backport/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spotless:
    if: github.repository == 'opensearch-project/flow-framework'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Spotless requires JDK 17+
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Spotless Check
        run: ./gradlew spotlessCheck
  build:
    needs: [spotless]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 17]
    name: Test JDK${{ matrix.java }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: actions/checkout@v4
        with:
          repository: opensearch-project/ml-commons
          ref: feature/agent_framework_dev
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal
      - uses: actions/checkout@v4
      - name: Build and Run Tests
        run: |
          ./gradlew check -x spotlessJava
      - name: Upload Coverage Report
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml