name: BWC
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'whitesource-remediate/**'
      - 'backport/**'
      - 'create-pull-request/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build-ff-linux:
    strategy:
      matrix:
        java: [21]
      fail-fast: false

    name: Test Flow Framework BWC
    runs-on: ubuntu-latest

    steps:
      # TEMPORARY until this is on Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Checkout Metadata Client
        uses: actions/checkout@v4
        with:
          repository: dbwiddis/opensearch-remote-metadata-sdk
          ref: main
          path: opensearch-remote-metadata-sdk
      - name: Publish to maven local
        working-directory: opensearch-remote-metadata-sdk
        run: ./gradlew publishToMavenLocal
      # end TEMPORARY code
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Checkout Flow Framework
        uses: actions/checkout@v4

      - name: Assemble Flow Framework
        run: |
          plugin_version=`./gradlew properties -q | grep "opensearch_build:" | awk '{print $2}'`
          echo plugin_version $plugin_version
          ./gradlew assemble
          echo "Creating ./src/test/resources/org/opensearch/flowframework/bwc/flow-framework/$plugin_version ..."
          mkdir -p ./src/test/resources/org/opensearch/flowframework/bwc/flow-framework/$plugin_version
          echo "Copying ./build/distributions/*.zip to ./src/test/resources/org/opensearch/flowframework/bwc/flow-framework/$plugin_version ..."
          ls ./build/distributions/
          cp ./build/distributions/*.zip ./src/test/resources/org/opensearch/flowframework/bwc/flow-framework/$plugin_version
          echo "Copied ./build/distributions/*.zip to ./src/test/resources/org/opensearch/flowframework/bwc/flow-framework/$plugin_version ..."
          ls ./src/test/resources/org/opensearch/flowframework/bwc/flow-framework/$plugin_version
      - name: Run Flow Framework Backwards Compatibility Tests
        run: |
          echo "Running backwards compatibility tests ..."
          ./gradlew bwcTestSuite -Dtests.security.manager=false
